### ISSUE TITLE
Invalid client_id

### ISSUE THREAD

**Issue by lukasz-zak** [rdio/jsapi-examples#5]
Hello,

I'm trying to grab api like you show in example:

//Register your app at http://www.rdio.com/developers/create/ and replace client_id below with yours 

```
<script src="https://www.rdio.com/api/api.js?client_id=ppJo1acOvcWl8ZlpTnXUkA"></script>
```

At first point the url not work. So I'm trying to change your client_id with mine **key** from this site: http://developer.rdio.com/apps/mykeys but I see then invalid client_id information.

What I'm doing wrong?

**Comment by dragongears** [comment]
I am having the same issue.

**Comment by dasevilla** [comment]
This project is part of our beta JavaScript API, see http://goo.gl/yzl8p for more information.
